sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"  
  - docker build -t jhcho7510/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jhcho7510/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"
